### ISSUE TITLE
Why is this the default TOML gem on rubygems.org?

### ISSUE THREAD

**Issue by brandondrew** [jm/toml#42]
This appears to be neither up-to-date, nor the original TOML gem.  Is there a reason for this to be the default gem given by rubygems.org when someone puts `gem 'toml'` in their Gemfile?

If not, is there a way for the author(s) of this gem to correct the entry on rubygems.org, or does that matter need to be brought up elsewhere?

If it needs to be taken up elsewhere, would I have the support of this gems author(s) if I request that the gem under `toml-lang` be used instead?

**Comment by parkr** [comment]
It's named toml so that's why you get ot when you download the toml gem.

**Comment by parkr** [comment]
I havent had much time to patch it up with the new spec of toml. Do you have time to help?

**Comment by brandondrew** [comment]
Sorry!  I didn't notice that mojombo's repo (now under toml-lang) is just the spec.
