### ISSUE TITLE
Failed to parse numbers with underscores

### ISSUE THREAD

**Issue by ivanovaleksey** [jm/toml#46]
Hi.

It is said [here](https://github.com/toml-lang/toml#integer) that
> For large numbers, you may use underscores to enhance readability

but it seems to be broken.

```
content = <<-TOML
foo = 10_000_000
TOML
parser = TOML::Parser.new(content).parsed

Failed to match sequence (ALL_SPACE (TABLE / TABLE_ARRAY / KEY_VALUE / COMMENT_LINE){0, } ALL_SPACE) at line 1 char 1.
`- Don't know what to do with "foo = 10_0" at line 1 char 1.
```

Is it `parslet` related issue?

**Comment by mhmoudgmal** [comment]
@ivanovaleksey now it is supported. :)

**Comment by ivanovaleksey** [comment]
@mhmoudgmal nicely done! Can I close the issue?

**Comment by mhmoudgmal** [comment]
@ivanovaleksey Yes, I think so.
