### ISSUE TITLE
Release 0.3.0 to rubygems

### ISSUE THREAD

**Issue by ramereth** [jm/toml#64]
We're starting to have problems due to the pessimistic version lock on parslet which exists in 0.2.0. I see that this is fixed in the master branch here however it has not been released yet. You can see more detail on the issue we're hitting here inspec/inspec#5389.

**Comment by ramereth** [comment]
@jm @dirk are either of you available to help push out a release? It seems you both have the power on rubygems. Thank you!

**Comment by jm** [comment]
@ramereth I'll take care of it tonight!  Sorry about the delay!

**Comment by hlascelles** [comment]
Gentle nudge for this please!

**Comment by bastelfreak** [comment]
hey @jm ,
thanks for pushing 0.3.0 to rubygems. Can you please push the git tag as well? I'm trying to package toml for Arch Linux and that requires me to build it from source.

**Comment by jm** [comment]
@bastelfreak Done!
